kind: pipeline
name: default

steps:
- name: build
  image: node
  commands:
  - bash ./build.sh
  - bash ./deploy.sh
  environment:
    S3_ACCESS_KEY:
      from_secret: S3_ACCESS_KEY
    S3_ACCESS_SECRET:
      from_secret: S3_ACCESS_SECRET
  when:
    branch:
    - master
trigger:
  event:
    exclude:
    - pull_request
