version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '4468:5432'
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    depends_on:
      - "db"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: db
            port: 5432
            user: postgres
            password: example
            database: postgres
        managementApiSecret: supersecret

  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea #seemingly ignored
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - SECRET_KEY=giteasecretkey
      - ENABLE_SWAGGER=false
      - APP_NAME=Platform
      #iflive - RUN_MODE=prod
      # - ROOT_URL=publicurl.com
    restart: always
    volumes:
      - ./gitea:/data
    ports:
      - "4469:3000"
      - "222:22"
    depends_on:
      - db

  mgmt:
    image: node
    ports:
      - '4467:4467'
    depends_on:
      - "db"
      - "prisma"
    volumes:
      - './mgmt:/app'
    working_dir: '/app'
    command: ["yarn", "dev"]
    environment:
      PRISMA_MANAGEMENT_URL: http://prisma:4466/management
      PRISMA_MANAGEMENT_API_SECRET: supersecret
      PORT: 4467
      GITEA_WEBHOOK_SECRET: gitea-secret
      GITEA_URL: http://gitea:3000
      GITEA_MACHINE_USER: machine
      GITEA_MACHINE_PASSWORD: Password123!
      BUILDER_BUCKET_ID: builder-bucket-key-id-7
      BUILDER_BUCKET_SECRET: builder-bucket-secret
      ENDPOINTS_ENDPOINT: http://endpoints:4470
      
      S3_ENDPOINT: http://files:9000
      FILEMANAGER_ENDPOINT: http://file-manager:4472
      PLATFORM_DB_TYPE: pg # knex db type
      PLATFORM_DB_HOST: db
      PLATFORM_DB_PORT: 5432
      PLATFORM_DB_NAME: platform #seemingly ignored
      PLATFORM_DB_USER: platform
      PLATFORM_DB_PASSWORD: platform

  dind:
    image: docker:dind
    privileged: true
    volumes:
      - './endpoints/certs:/certs-output'
    environment:
      DOCKER_TLS_CERTDIR: /certs-output
    expose:
      - 2375
      - 2376

  endpoints:
    build: ./endpoints
    privileged: true
    ports:
      - '4470:4470'
    depends_on:
      - "db"
      - "prisma"
      - "dind"
    volumes:
      - './endpoints:/app'
    working_dir: '/app'
    command: ["yarn", "dev"]
    environment:
      PRISMA_MANAGEMENT_URL: http://prisma:4466/management
      PRISMA_MANAGEMENT_API_SECRET: supersecret
      PORT: 4470
      DOCKER_HOSTNAME: dind
      DOCKER_HOST: tcp://dind:2376
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

      PLATFORM_DB_TYPE: pg # knex db type
      PLATFORM_DB_HOST: db
      PLATFORM_DB_PORT: 5432
      PLATFORM_DB_NAME: platform #seemingly ignored
      PLATFORM_DB_USER: platform
      PLATFORM_DB_PASSWORD: platform

      BUILDER_BUCKET_ID: builder-bucket-key-id-7
      BUILDER_BUCKET_SECRET: builder-bucket-secret
      S3_ENDPOINT: http://files:9000

  files:
    image: minio/minio
    ports:
      - '4471:9000'
    volumes:
      - './tmp/files:/data'
    command: ["server", "/data"]
    environment:
      PORT: 4471
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY

  file-manager:
    build: ./file-manager
    ports:
      - '4472:4472'
    depends_on:
      - "db"
      - "files"
    volumes:
      - './file-manager:/app'
    working_dir: '/app'
    command: ["yarn", "dev"]
    environment:
      PORT: 4472
      MC_HOST_minio: http://AKIAIOSFODNN7EXAMPLE:wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY@files:9000
  
  dev-endpoint:
    image: node
    ports:
      - '4489:4489'
    volumes:
      - './dev-endpoint:/app'
    working_dir: '/app'
    command: ["yarn", "dev"]
    environment: 
      PORT: 4489
      CHILD_PORT: 4501
      CHILD_DEBUG_PORT: 4502