version: '3.1'

services:
  dns:
    image: resystit/bind9
    ports:
      - '53:53'
      - '53:53/udp'
    volumes:
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/onultima.local.zone:/etc/bind/onultima.local.zone
      - ./dns/local.zone:/etc/bind/local.zone

  db:
    image: postgres
    restart: always
    ports:
      - '4468:5432'
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

  gitea:
    image: gitea/gitea:1.12.0-rc1
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea #seemingly ignored
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - SECRET_KEY=giteasecretkey
      - ENABLE_SWAGGER=false
      - APP_NAME=Platform
      #iflive - RUN_MODE=prod
      # - ROOT_URL=publicurl.com
      - GITEA_CUSTOM=/custom
    restart: always
    volumes:
      - ./tmp/gitea:/data
      - ./gitea:/custom
    ports:
      - "4469:3000"
      - "222:22"
    depends_on:
      - db

  mgmt:
    image: node
    ports:
      - '4467:4467'
      - '4497:4497'
    depends_on:
      - "db"
    volumes:
      - './mgmt:/app'
      - './github-app.pem:/github-app.pem'
    working_dir: '/app'
    command: ["yarn", "dev"]
    env_file:
      - secrets.env
    environment:
      PORT: 4467
      GITEA_WEBHOOK_SECRET: gitea-secret
      GITEA_URL: http://gitea:3000
      GITEA_MACHINE_USER: machine
      GITEA_MACHINE_PASSWORD: Password123!
      BUILDER_BUCKET_ID: builder-bucket-key-id-7
      BUILDER_BUCKET_SECRET: builder-bucket-secret
      ENDPOINTS_ENDPOINT: http://endpoints:4470

      S3_ENDPOINT: http://files:9000
      FILEMANAGER_ENDPOINT: http://file-manager:4472

      PLATFORM_DB_TYPE: pg # knex db type
      PLATFORM_DB_HOST: db
      PLATFORM_DB_PORT: 5432
      PLATFORM_DB_NAME: platform #seemingly ignored
      PLATFORM_DB_USER: platform
      PLATFORM_DB_PASSWORD: platform

      ROUTER_MGMT_ENDPOINT: http://router-mgmt:4487

      GITEA_COOKIE_NAME: sessionid
      JWT_SECRET: 9KvXNgRVquPnkKkSDN
      AUTH_REDIRECT: http://build.onultima.local:4480/user/login/complete
      ELEVATED_AUTH_REDIRECT: http://build.onultima.local:4480/user/login/elevated-complete

      PUBLIC_ROUTE_ROOT_PROTOCOL: http
      PUBLIC_ROUTE_ROOT_PORT: 4480

      ES_USERNAME: elastic
      ES_PASSWORD: Password123!
      KIBANA_ENDPOINT: http://kibana:5601/kibana
      ADMIN_USERNAME: joshbalfour

      PLATFORM_DBA_USER: postgres
      PLATFORM_DBA_PASSWORD: example

      SALT: 9KvXN2783FHDSJkKkSDN

      TEMPLATE_OWNER_GITEA_USERNAME: joshbalfour

      PG_BROKER_PORT: 4497
      PUBLIC_ROUTE_ROOT: onultima.local
      PUBLIC_IPV4: '78.46.16.197'
      PUBLIC_IPV6: 2a01:4f8:201:206f::2

      INTERNAL_MGMT_ENDPOINT: http://192.168.1.112:4467
      REGISTRY_CACHE_ENDPOINT: http://192.168.1.112:4493/

      GITHUB_APP_KEY_LOCATION: /github-app.pem

      CHROME_EXT_ID: fipcokpepeolmgaholhadaaegcjkoknb

  dind:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_VERIFY: ""
      DOCKER_TLS_CERTDIR: /certs-output
    volumes:
      - './tmp/docker-certs:/certs-output'
    expose:
      - 2375
      - 2376
      - 2377
      - 4789
      - 7946 

  dind-worker:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs-output
    volumes:
      - './tmp/docker-certs:/certs-output:ro'
    expose:
      - 2375
      - 2376
      - 2377
      - 4789
      - 7946

  endpoints:
    build: ./endpoints
    privileged: true
    ports:
      - '4470:4470'
    depends_on:
      - "db"
      - "dind"
    volumes:
      - './endpoints:/app'
      - './tmp/docker-certs:/docker-certs'
    working_dir: '/app'
    command: ["yarn", "dev"]
    environment:
      PORT: 4470
      DOCKER_HOSTNAME: dind
      DOCKER_HOST: tcp://dind:2376
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

      PLATFORM_DB_TYPE: pg # knex db type
      PLATFORM_DB_HOST: db
      PLATFORM_DB_PORT: 5432
      PLATFORM_DB_NAME: platform #seemingly ignored
      PLATFORM_DB_USER: platform
      PLATFORM_DB_PASSWORD: platform

      BUILDER_BUCKET_ID: builder-bucket-key-id-7
      BUILDER_BUCKET_SECRET: builder-bucket-secret
      S3_ENDPOINT: http://files:9000

      GELF_ADDRESS: udp://logstash:12201
      MGMT_ENDPOINT: http://mgmt:4467

      CONTAINER_MANAGEMENT: swarm
      SWARM_LISTEN_ADDRESS: 0.0.0.0
      SWARM_ADVERTISE_ADDRESS: eth0

      CERTS_FOLDER: /docker-certs/client

  files:
    image: minio/minio
    ports:
      - '4471:9000'
    volumes:
      - './tmp/files:/data'
    command: ["server", "/data"]
    environment:
      PORT: 4471
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY

  file-manager:
    build: ./file-manager
    ports:
      - '4472:4472'
    depends_on:
      - "db"
      - "files"
    volumes:
      - './file-manager:/app'
    working_dir: '/app'
    command: ["yarn", "dev"]
    environment:
      PORT: 4472
      MC_HOST_minio: http://AKIAIOSFODNN7EXAMPLE:wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY@files:9000

  router-mgmt:
    image: node
    ports: 
      - '4487:4487'
      - '4997:4497'
    volumes:
      - './router:/app'
      - './tmp/router:/configs'
    working_dir: '/app'
    command: ["yarn", "dev"]
    environment:
      PORT: 4487
      
      PLATFORM_DB_TYPE: pg # knex db type
      PLATFORM_DB_HOST: db
      PLATFORM_DB_PORT: 5432
      PLATFORM_DB_NAME: platform #seemingly ignored
      PLATFORM_DB_USER: platform
      PLATFORM_DB_PASSWORD: platform

      CONFIG_DIR: /configs

      PUBLIC_ROUTE_ROOT: onultima.local
      PUBLIC_ROUTE_ROOT_PROTOCOL: http
      PUBLIC_ROUTE_ROOT_PORT: 4480

      MGMT_ENDPOINT: http://mgmt:4467
      ENDPOINTS_ENDPOINT: http://endpoints:4470
      TRAEFIK_ENDPOINT: http://router:8080
      GITEA_ENDPOINT: http://gitea:3000
      FRONTEND_ENDPOINT: http://frontend:4491
      GITEA_COOKIE_NAME: sessionid
      KIBANA_ENDPOINT: http://kibana:5601
      PGBROKER_ENDPOINT: tcp://mgmt:4497
      S3_ENDPOINT: http://files:9000

      # CERT_RESOLVER:
      # CERT_RESOLVER_HTTP:

  frontend:
    image: node
    ports: 
      - '4491:4491'
    volumes:
      - './frontend:/app'
    working_dir: '/app'
    command: ["yarn", "start"]
    environment:
      PORT: 4491
      CI: "true" # https://github.com/facebook/create-react-app/issues/8688#issuecomment-602084087
      MGMT_ENDPOINT: http://mgmt:4467

  router:
    image: traefik:v2.2
    command: --api.insecure=true --providers.file.directory=/config --providers.file.watch=true --api=true
    volumes:
      - './tmp/router:/config'
    ports:
      - '4480:80'
      - '4488:8080'

  elasticsearch:
    image: elasticsearch:7.6.2
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=Password123!

  logstash:
    image: logstash:7.6.2
    depends_on: 
      - elasticsearch
    ports:
      - 12201:12201/udp
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment: 
      XPACK.MONITORING.ENABLED: "true"
      XPACK.MONITORING.ELASTICSEARCH.HOSTS: "[\"http://elasticsearch:9200\"]"
      XPACK.MONITORING.ELASTICSEARCH.USERNAME: elastic
      XPACK.MONITORING.ELASTICSEARCH.PASSWORD: Password123!

  kibana:
    image: kibana:7.6.2
    depends_on:
      - elasticsearch
    ports:
      - 4492:5601
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=Password123!
      - XPACK_MONITORING_ELASTICSEARCH_USERNAME=elastic
      - XPACK_MONITORING_ELASTICSEARCH_PASSWORD=Password123!
      - XPACK_SECURITY_ENCRYPTIONKEY=something_at_least_32_characterssomething_at_least_32_characters
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=true

  registry-cache:
    image: nginx
    ports:
      - 4493:80
    volumes:
      - ./registry-cache/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  es-data:
