version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '4468:5432'
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    depends_on:
      - "db"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: db
            port: 5432
            user: postgres
            password: example
            database: postgres
        managementApiSecret: supersecret

  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea #seemingly ignored
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - SECRET_KEY=giteasecretkey
      - ENABLE_SWAGGER=false
      - APP_NAME=Platform
      #iflive - RUN_MODE=prod
      # - ROOT_URL=publicurl.com
    restart: always
    volumes:
      - ./gitea:/data
    ports:
      - "4469:3000"
      - "222:22"
    depends_on:
      - db

  mgmt:
    image: node
    ports:
      - '4467:4467'
    depends_on:
      - "db"
      - "prisma"
    volumes:
      - './mgmt:/app'
    working_dir: '/app'
    command: ["yarn", "dev"]
    environment:
      PRISMA_MANAGEMENT_URL: http://prisma:4466/management
      PRISMA_MANAGEMENT_API_SECRET: supersecret
      PORT: 4467
      GITEA_WEBHOOK_SECRET: gitea-secret
      GITEA_URL: http://gitea:3000
      GITEA_MACHINE_USER: machine
      GITEA_MACHINE_PASSWORD: Password123!
      BUILDER_BUCKET_ID: builder-bucket-key-id-7
      BUILDER_BUCKET_SECRET: builder-bucket-secret
      ENDPOINTS_ENDPOINT: http://endpoints:4470

      S3_ENDPOINT: http://files:9000
      FILEMANAGER_ENDPOINT: http://file-manager:4472

      PLATFORM_DB_TYPE: pg # knex db type
      PLATFORM_DB_HOST: db
      PLATFORM_DB_PORT: 5432
      PLATFORM_DB_NAME: platform #seemingly ignored
      PLATFORM_DB_USER: platform
      PLATFORM_DB_PASSWORD: platform

      STATIC_ENDPOINT: http://web-files:80 #internal

      ROUTER_MGMT_ENDPOINT: http://router-mgmt:4487

  dind:
    image: docker:dind
    privileged: true
    volumes:
      - './endpoints/certs:/certs-output'
    environment:
      DOCKER_TLS_CERTDIR: /certs-output
    expose:
      - 2375
      - 2376

  endpoints:
    build: ./endpoints
    privileged: true
    ports:
      - '4470:4470'
    depends_on:
      - "db"
      - "prisma"
      - "dind"
    volumes:
      - './endpoints:/app'
    working_dir: '/app'
    command: ["yarn", "dev"]
    environment:
      PRISMA_MANAGEMENT_URL: http://prisma:4466/management
      PRISMA_MANAGEMENT_API_SECRET: supersecret
      PORT: 4470
      DOCKER_HOSTNAME: dind
      DOCKER_HOST: tcp://dind:2376
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

      PLATFORM_DB_TYPE: pg # knex db type
      PLATFORM_DB_HOST: db
      PLATFORM_DB_PORT: 5432
      PLATFORM_DB_NAME: platform #seemingly ignored
      PLATFORM_DB_USER: platform
      PLATFORM_DB_PASSWORD: platform

      BUILDER_BUCKET_ID: builder-bucket-key-id-7
      BUILDER_BUCKET_SECRET: builder-bucket-secret
      S3_ENDPOINT: http://files:9000

  files:
    image: minio/minio
    ports:
      - '4471:9000'
    volumes:
      - './tmp/files:/data'
    command: ["server", "/data"]
    environment:
      PORT: 4471
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY

  file-manager:
    build: ./file-manager
    ports:
      - '4472:4472'
    depends_on:
      - "db"
      - "files"
    volumes:
      - './file-manager:/app'
    working_dir: '/app'
    command: ["yarn", "dev"]
    environment:
      PORT: 4472
      MC_HOST_minio: http://AKIAIOSFODNN7EXAMPLE:wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY@files:9000

  web-files:
    image: nginx
    volumes:
      - ./web-files/nginx.conf:/etc/nginx/conf.d/nginx.conf.template
    ports:
      - "4473:80"
    environment:
      MINIO_URL: http://files:9000
    command: /bin/bash -c "envsubst '$$MINIO_URL' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  router-mgmt:
    image: node
    ports: 
      - '4487:4487'
    volumes:
      - './router:/app'
      - './tmp/router:/configs'
    working_dir: '/app'
    command: ["yarn", "dev"]
    environment:
      PORT: 4487
      
      PLATFORM_DB_TYPE: pg # knex db type
      PLATFORM_DB_HOST: db
      PLATFORM_DB_PORT: 5432
      PLATFORM_DB_NAME: platform #seemingly ignored
      PLATFORM_DB_USER: platform
      PLATFORM_DB_PASSWORD: platform

      CONFIG_DIR: /configs

      PUBLIC_ROUTE_ROOT: onultima.local
      PUBLIC_ROUTE_ROOT_PROTOCOL: http
      PUBLIC_ROUTE_ROOT_PORT: 4480

      MGMT_ENDPOINT: http://mgmt:4467
      ENDPOINTS_ENDPOINT: http://endpoints:4470
      TRAEFIK_ENDPOINT: http://router:8080

  router:
    image: traefik:v2.2
    command: --api.insecure=true --providers.file.directory=/config --providers.file.watch=true --api=true
    volumes:
      - './tmp/router:/config'
    ports:
      - '4480:80'
      - '4488:8080'
